name: Continuos Integration

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker build --progress=plain --target=build .
      - name: Unit tests
        run: docker build --progress=plain --target unit_tests .
