name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Workdir
        run: cd test/
      - name: Integration tests
        run: docker build \
          --progress=plain \
          --target=integration_tests \
          --build-arg TEMPLATE_PACKAGE_VERSION=$PACKAGE_RELEASE \
          .
        env:
          PACKAGE_RELEASE: ${{ github.ref_name }}
